### 
GET http://localhost:5777 HTTP/1.1


###
GET http://localhost:5777/version HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5778/api HTTP/1.1
Content-Type: application/json

{
    "type": "SubmitTaskRequest",
    "request": {
        "task": {
            "type": "Swarmr.Base.Tasks.LogTask",
            "task": {
                "message": "hello world"
            }
        }
    }
}

### sm/test/result1
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "RunJobRequest",
    "request": {
        "job": {
            "setup": [
                "sm/test/exe",
                "sm/test/data1"
            ],
            "execute": [
                { "exe": "Sum.exe", "args": "data1.txt out.txt" }
            ],
            "collect": [
                "out.txt",
                "."
            ],
            "result": "sm/test/result1"
        }
    }
}


### sm/test/result2
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "RunJobRequest",
    "request": {
        "job": {
            "setup": [
                "sm/test/exe",
                "sm/test/data2"
            ],
            "execute": [
                { "exe": "Sum.exe", "args": "data2.txt out.txt" }
            ],
            "collect": [
                "out.txt",
                "."
            ],
            "result": "sm/test/result2"
        }
    }
}

### sm/test/result3
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "RunJobRequest",
    "request": {
        "job": {
            "setup": [
                "sm/test/exe",
                "sm/test/data3"
            ],
            "execute": [
                { "exe": "Sum.exe", "args": "data3.txt out.txt" }
            ],
            "collect": [
                "out.txt",
                "."
            ],
            "result": "sm/test/result3"
        }
    }
}

### sm/test/result1
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "SubmitJobRequest",
    "request": {
        "job": {
            "setup": [
                "sm/test/exe",
                "sm/test/data1"
            ],
            "execute": [
                { "exe": "Sum.exe", "args": "work 5" }
            ],
            "collect": [
                "."
            ],
            "result": "sm/test/work13"
        }
    }
}

### set secret
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "SetSecretRequest",
    "request": {
        "key": "nugetkey",
        "value": "b0b58375-e370-477b-9db0-51b1e5235e45"
    }
}

### list secrets
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "ListSecretsRequest",
    "request": {
    }
}

### list active jobs
POST http://localhost:5777/api HTTP/1.1
Content-Type: application/json

{
    "type": "ListActiveJobsRequest",
    "request": {
    }
}